### ISSUE TITLE
Field Positioning System

### ISSUE THREAD

**Issue by open-sourceress** [FRC4131/RecycleRush2015#3]
The end result should be a method that takes two ints/doubles, an x- and y-coordinate on the field. The method will block (using `Timer.delay()`) until the robot has reached the specified coordinates on the field

**Comment by open-sourceress** [comment]
In order for this to work, we will most likely need to read the accelerometer, encoders, or both in order to determine where we're going in order to find where we are.. We can determine where we are at the start using `DriverStation.getInstance().getPosition()` (1, 2, or 3 for left, center, and right stations)

**Comment by Naoki95957** [comment]
Okay, I was curious how were going to be able to get our locations and distance traveling. That's why I brought up the question in autonomous. It's all technically possible through the encoders alone and more accurately so with the accelerometer, but we'll need some pretty sophisticated way of analyzing the data. The accelerometer should approximate where we are very simply, but the encoders will be interesting due to the fact that when strafing we practically have wheels spinning in every direction.

**Comment by FlintWeiss** [comment]
That's a good callout.

Here's a crazy idea:

In magazines like Road and Track, you often see pictures of road-testing cars with a wheel strapped onto the back to accurately measure distance.

I wonder if there are sensors that are like casters that can measure distance and direction. Something like that would show actual distance traveled and in which direction. Two in opposing corners might be redundant enough to handle a caster being airborne going up and down a ramp.

Obviously, if a software approach works, that's better because we already have all the parts. But I wanted to mention a physical idea, just in case.

~ sent from my Fire phone ~

On February 3, 2015, at 7:32 AM, Naoki notifications@github.com wrote:

Okay, I was curious how were going to be able to get our locations and distance traveling. That's why I brought up the question in autonomous. It's all technically possible through the encoders alone and more accurately so with the accelerometer, but we'll need some pretty sophisticated way of analyzing the data. The accelerometer should approximate where we are very simply, but the encoders will be interesting due to the fact that when strafing we practically have wheels spinning in every direction.

**Comment by Naoki95957** [comment]
XD I was thinking of an extra wheel for measurement too! I was kinda wondering what would happen if we strapped an optical on the underside. like a computer mouse XD. Would it be possible to read data from this? It'd practically be touching the ground tho.

**Comment by open-sourceress** [comment]
The optical mouse idea would be awesome, if it didn't mean we have to do image processing twice over. The extra casters would require a swerve-drive setup, but with sensors instead of motors. I think the best way to go would be with software and the sensors we already have.

**Comment by open-sourceress** [comment]
I mentioned using the accelerometer because of the interesting problem of encoders switching directions. However, you are correct that encoders would be more precise. We could just do `if(frontLeft.getDirection() != rearLeft.getDirection())` if necessary.

**Comment by Naoki95957** [comment]
I noticed a few reverts to the code (under pidtalon). Just fyi the encoders are different front from back by 110 pulses. fronts are 250 and rears are 360. If it's accounted for, great.

**Comment by FlintWeiss** [comment]
I was thinking that the optical mice do all the image processing onboard and then output x/y coordinates.

I did some searching tonight and found this which seems like the best link so far:http://www.wildcircuits.com/2013/03/optical-mouse-hacking.html . If we find the right control board, it will output on I2C.

There was also a reference on Chief Delphi but it was pretty old and didn’t have much current info. 

In fact it doesn’t seem to be commonly talked about much which suggests that either there are now inexpensive off the shelf solutions (maybe we just have to figure out what kind of sensor subsystem to search for), or that it didn’t work out so well. I’m inclined to believe in the former – you don’t have to hack optical mice anymore but it’ll take some more searching to confirm.

http://hackaday.com/2013/04/03/adding-an-optical-mouse-sensor-to-an-autonomous-vehicle/

**Comment by open-sourceress** [comment]
I think it may be the latter, especially because of the scoring platforms. When we go up and down ramps, the mouse will be airborne. I've noticed that when you hold a mouse above a mousepad, you get partial reception anywhere less than a centimeter up. Beyond that, it's gone.

**Comment by open-sourceress** [comment]
Naoki, when I tested the PIDTalon class, setting the distance per pulse did not seem to be necessary. I did not incorporate that functionality into PIDTalon, and all of the wheels seemed to rotate equally. (This is a visual observation, not from the encoder readings; encoders would always read the same value, because they are being used to equalize the motor output.)

**Comment by open-sourceress** [comment]
Oops.

**Comment by Naoki95957** [comment]
In what way are we getting distance then? additionally is there any other way but to eye-ball whether or not the wheels are at equal rpm? Id rather calculate speed from distance than calculate distance from speed.

**Comment by open-sourceress** [comment]
Using `PIDTalon.getDistance()` without setting a distance per pulse seems to work for equalizing values across the wheels. And the way we could make sure the wheels are going the same speed is hooking a potentiometer onto each axle.

**Comment by Naoki95957** [comment]
Can we accurately move x amount of feet? Or accurately read x? The thing is idk how (logically) we're getting distance. Nothing but default is running the distances, the ticks are at different intervals, and it's not like the code finds our wheel diameter. If it just avgs rpms, it's based on either pulses or the encoder actually knows what a rev is. If all the encoders know are pulses, the fronts will go ever slightly faster due to having larger gaps between pulses. If running distance without manually hard coding it in works then there's no problem, but... We NEED the cable adapters so we can test the bot :/

**Comment by open-sourceress** [comment]
The FPS has been set aside due to the difficulty involved in getting it to work. If we have any copious amounts of time somewhere in the future, we may return to it.
