### ISSUE TITLE
Code Organization

### ISSUE THREAD

**Issue by open-sourceress** [FRC4131/RecycleRush2015#5]
Split code into multiple files (preferably one per task to reduce Git merge problems) to make it more organized and easier to read.

**Comment by Naoki95957** [comment]
Btw the robot is currently wired incorrectly. Since the talons are done through CAN I don't know how I'd rearrange them (unless passing them in a different order on the drive does it). Also the elevator is hooked up to pwm 0, and the front wheels (for the totes) is in 1. They are hooked up to normal talons

**Comment by Naoki95957** [comment]
The orientation of coffin bot got turned sideways (to the right) when mounted on the new bot.

**Comment by open-sourceress** [comment]
I thought I fixed the motors last night! You plug in via USB, go to 172.22.11.2, and change the CAN IDs from there. What do you mean, it was turned sideways? Is the gyro reading 90 off, or is this still the motors?

**Comment by Naoki95957** [comment]
No, that was a status from Monday. The board is oriented 90 degrees clockwise. The motors were hooked up to the wrong talons then. Idk about it now. I'll be there tomorrow. I have an idea to greatly improve the accuracy of the goTo method. Instead of setting its position to the differences in calculations, set it to the differences in raw values. This will make each travel execution as accurate as the next instead of building on top of each other.

-------- Original message --------

**Comment by open-sourceress** [comment]
I'll be there as well, so we can work it out together. The gyro reset should make it re-orient. We'll figure out CANNet. What do you mean, difference in raw vs calculations?

**Comment by Naoki95957** [comment]
Currently it solves it's distance by adding/subtracting the distances it's aiming for. However it stops after reaching it's destination and may not be accurate. Instead of using differences in point values it will update using differences in encoder/gyro values.

-------- Original message --------

**Comment by open-sourceress** [comment]
Alright. Let's figure out the motors being wonky, then work on that.

**Comment by open-sourceress** [comment]
The code is now organized.
- Every system, ie the drive base, the sensors, the conveyor and wheels, will have its own file.
- The system's constructor will take port numbers for everything required in the system, and a reference to any other required systems (ie the drive base requires access to the sensors for the gyro).
- The Robot will keep an instance of each subsystem, and control each subsystem as needed.
